spring.application.name=alquiler-api

# === Configuración de base de datos (ejemplo MySQL) ===
spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_eventos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=isra224
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Configuración del servidor de correo con Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# TU CORREO PERSONAL AQUÍ:
spring.mail.username=imurillo682@gmail.com
# LA CONTRASEÑA DE APLICACIÓN DE 16 DÍGITOS:
spring.mail.password=dgsb komo dubu tczo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

