spring.application.name=jugadores_barcelona

# Configuración de conexión H2 en memoria
spring.datasource.url=jdbc:h2:mem:barcadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Spring Boot creará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# IMPORTANTE: Esto hace que data.sql se ejecute DESPUÉS de crear las tablas
spring.jpa.defer-datasource-initialization=true